# Generated by Django 4.2.11 on 2024-04-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecoderelation',
            name='created_at',
        ),
    ]
