# Generated by Django 4.2.11 on 2024-04-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_activated_invite_code_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.CharField(default=None, null=True),
        ),
    ]
