# Generated by Django 4.2.11 on 2024-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated_invite_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default=None),
        ),
    ]
