# Generated by Django 4.2.11 on 2024-04-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_activated_invite_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
