version: '3'

services:
  db:
    image: postgres:latest
    container_name: referral_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: referal_system
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
